#!/bin/bash

function tg_sendText() {
curl -s "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" \
-d "parse_mode=html" \
-d text="${1}" \
-d chat_id=$CHAT_ID \
-d "disable_web_page_preview=true"
}

function tg_sendFile() {
curl -F chat_id=$CHAT_ID -F document=@${1} -F parse_mode=markdown https://api.telegram.org/bot$BOT_TOKEN/sendDocument
}


cd /tmp

tg_sendText "Uploading ccache to Drive.."

# Compress function with pigz for faster compression
com () 
{ 
    tar --use-compress-program="pigz -k -$2 " -cf $1.tar.gz $1
}

time com ccache 1 # Compression level 1, its enough

curl --upload-file /tmp/ccache.tar.gz http://transfer.sh/ccache.tar.gz | tee ccacheurl.txt
tg_sendFile ccacheurl.txt
tg_sendText "Sucessfully uploaded ccache to Drive.."
